# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-14 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formExample', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='college_city',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
